# Generated by Django 4.0.6 on 2023-02-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('explain_pk', models.AutoField(primary_key=True, serialize=False)),
                ('explain_id', models.CharField(max_length=10)),
                ('explain_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_pk', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('team_member', models.ManyToManyField(related_name='team_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitResult',
            fields=[
                ('submit_pk', models.AutoField(primary_key=True, serialize=False)),
                ('submit_file', models.FileField(upload_to='submits/')),
                ('submit_score', models.DecimalField(decimal_places=4, max_digits=6)),
                ('submit_create', models.DateTimeField(auto_now_add=True)),
                ('submit_team_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_team', to='board.team')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('leader_pk', models.AutoField(primary_key=True, serialize=False)),
                ('leader_submit_pk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_submit', to='board.submitresult')),
            ],
        ),
    ]
