# Generated by Django 4.0.6 on 2023-02-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_pk', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.ImageField(upload_to='')),
            ],
        ),
    ]
