# Generated by Django 4.0.6 on 2023-02-06 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitresult',
            name='submit_user_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submit_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
