# Generated by Django 4.0.6 on 2023-02-07 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_submitresult_submit_user_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='leader_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
