# Generated by Django 4.0.6 on 2023-02-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_leaderboard_leader_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitresult',
            name='submit_name',
            field=models.CharField(default='2', max_length=256),
            preserve_default=False,
        ),
    ]
