# Generated by Django 4.0.6 on 2023-02-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_submitresult_submit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitresult',
            name='submit_create',
        ),
        migrations.AddField(
            model_name='submitresult',
            name='submit_leader',
            field=models.BooleanField(default=False),
        ),
    ]
