# Generated by Django 4.0.6 on 2023-02-07 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_remove_submitresult_submit_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitresult',
            name='submit_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
