# Generated by Django 4.0.6 on 2023-02-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_submitresult_submit_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderTime',
            fields=[
                ('leader_pk', models.AutoField(primary_key=True, serialize=False)),
                ('leader_create', models.DateTimeField(auto_now=True)),
                ('leader_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_team', to='board.team')),
            ],
        ),
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
    ]
