on:
  pull_request:
    branches:
      - migrate
    types: [closed]

jobs:
  jenkins:
    if: github.event.pull_request.merged == true
    name: Jenkins-action
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "jaram-workshop"